project: EMURoutingTracker.xcodeproj
schemes:
- EMURoutingTracker
- EMURoutingTrackerFramework
- EMURoutingTrackerWidgetExtension
targets:
- EMURoutingTracker
- EMURoutingTrackerFramework
- EMURoutingTrackerWidgetExtension
